import zanahoria from './zanahoria.svg';
import lechuga from './lechuga.svg';
import pepino from './pepino.svg';

export const products = [
    {
        id: 1,
        name: 'Product 1',
        price: 100,
        description: 'Product 1 (100$)',
        image: zanahoria,
    },
    {
        id: 2,
        name: 'Product 2',
        price: 200,
        description: 'Product 2 (200$)',
        image: lechuga,
    },
    {
        id: 3,
        name: 'Product 3',
        price: 300,
        description: 'Product 3 (300$)',
        image: pepino,
    },
    {
        id: 4,
        name: 'Product 1',
        price: 100,
        description: 'Product 1 (100$)',
        image: zanahoria,
    },
    {
        id: 5,
        name: 'Product 2',
        price: 200,
        description: 'Product 2 (200$)',
        image: lechuga,
    },
    {
        id: 6,
        name: 'Product 3',
        price: 300,
        description: 'Product 3 (300$)',
        image: pepino,
    },
    {
        id: 7,
        name: 'Product 1',
        price: 100,
        description: 'Product 1 (100$)',
        image: zanahoria,
    },
    {
        id: 8,
        name: 'Product 2',
        price: 200,
        description: 'Product 2 (200$)',
        image: lechuga,
    },
    {
        id: 9,
        name: 'Product 3',
        price: 300,
        description: 'Product 3 (300$)',
        image: pepino,
    },
    {
        id: 10,
        name: 'Product 1',
        price: 100,
        description: 'Product 1 (100$)',
        image: zanahoria,
    },
    {
        id: 11,
        name: 'Product 2',
        price: 200,
        description: 'Product 2 (200$)',
        image: lechuga,
    },
    {
        id: 12,
        name: 'Product 3',
        price: 300,
        description: 'Product 3 (300$)',
        image: pepino,
    },
    {
        id: 13,
        name: 'Product 1',
        price: 100,
        description: 'Product 1 (100$)',
        image: zanahoria,
    },
    {
        id: 14,
        name: 'Product 2',
        price: 200,
        description: 'Product 2 (200$)',
        image: lechuga,
    },
    {
        id: 15,
        name: 'Product 3',
        price: 300,
        description: 'Product 3 (300$)',
        image: pepino,
    },
    {
        id: 16,
        name: 'Product 1',
        price: 100,
        description: 'Product 1 (100$)',
        image: zanahoria,
    },
    {
        id: 17,
        name: 'Product 2',
        price: 200,
        description: 'Product 2 (200$)',
        image: lechuga,
    },
    {
        id: 18,
        name: 'Product 3',
        price: 300,
        description: 'Product 3 (300$)',
        image: pepino,
    },
];